### ISSUE TITLE
Agent redundancy doesn't work as described in documentation

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-lbaasv1#80]
#### Agent Version
1.0.12

#### Operating System
any

#### OpenStack Release
Kilo +

#### Description
Per discussion with @mattgreene -- the agent redundancy described in the user guide doesn't actually exist. When an agent goes down permanently, communication with the pools it manages is lost. If attempts to bring the agent back online fail, all pools associated with that agent are basically useless. See #73.

**Comment by rayvon** [comment]
1. in one real private cloud /public cloud case , no end user will have only one stand alone network controller , it must be Cluster Controller .
2. as LBaaS public cloud service , the service can't stop working just because one LBaaS agent down
3. the design binding pool to one special agent-host is not support multi-agent solution , need re-design the whole multi-agent architecture
4. rabbit messsage queues are mirrored , but lack of lock/unlock method  , need to design one way to sync between all the LBaaS agents

**Comment by jputrino** [comment]
@rayvon - I'm copying your comments over to #73, which is the development issue; this issue is for documentation.

**Comment by mattgreene** [comment]
Removing the 'bug' label from this issue.  It is a known design constraint in an lbaasv1 multi-agent deployment and will be addressed with the lbaasv2 agent.
